version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage/app/public:/var/www/html/public/storage
      - ./docker/php/php.ini:/etc/php/7.2/php.ini
    ports:
      - "8080:80"
    networks:
      - mynet
  composer:
    image: composer:1.8
    restart: 'no'
    command: install
    volumes:
      - ./:/app
    networks:
      - mynet
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    networks:
      - mynet
  mysql:
    image: yobasystems/alpine-mariadb
    ports:
      - "8333:3306"
    expose:
      - '8333'
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: site
    networks:
      - mynet
#  node:
#    image: node:8.16-alpine
#    working_dir: /var/www/html
#    volumes:
#      - ./:/var/www/html
  supervisord:
    build:
      context: ./
      dockerfile: ./docker/supervisor/Dockerfile
    restart: always

#    environment:
#      SUPERVISOR_CONF_FILE: ./docker/supervisor/supervisor.conf
    volumes:
      - ./docker/supervisor/supervisord.conf:/etc/supervisord.conf
      - ./docker/supervisor/workers.ini:/etc/supervisor.d/workers.ini
#      - ./docker/supervisor/supervisor.conf:/etc/supervisor.d
      - ./:/var/www/html
    ports:
      - 6001:6001
    networks:
      - mynet
networks:
  mynet:
    driver: "bridge"
volumes:
  mysqldata:
  redisdata:
